backend: tf
eval: 300
early_stop: 30
epochs: 2
mod_list: []
dataset: light
name: experiment
seed: 42
quantization: false
verbose: 2
w_FLOPS: 0.33
w_HW: 0.33
lacc: 0.1
flops_th: 150000000
nparams_th: 2500000
opt: filtered
use_hw_cost: true
hw_backend: nvdla
created_at: '2026-02-13T17:30:02'
